#server:
#  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stakeholder?createDatabaseIfNotExist=true
    username: root
    password: 1qaz2wsx@
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create

    properties:
      hibernate:
        show_sql: true
        format_sql: true