
server:
  port: 8091
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/PasinduSandakelum/inventory-system-config-store
          search-paths:
            - '*service'

          force-pull: true





   
